# Generated by Django 2.0 on 2019-10-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_withdrawal', models.BooleanField(default=True)),
                ('allow_deposit', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
