# Generated by Django 2.0 on 2019-12-24 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_withdrawal', models.BooleanField(default=True)),
                ('allow_deposit', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),

    ]
