# Generated by Django 2.0 on 2019-12-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='remuneration',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.DeleteModel(
            name='Remuneration',
        ),
    ]
