# Generated by Django 2.0 on 2018-01-30 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='description')),
                ('information', models.CharField(blank=True, max_length=100, verbose_name='transaction information')),
                ('reference', models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='fees')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='transaction status')),
                ('trans_code', models.CharField(blank=True, max_length=20, verbose_name='transaction code')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('thirdparty_reference', models.CharField(db_index=True, max_length=30, verbose_name='third party reference')),
                ('nsp', models.CharField(blank=True, max_length=30, null=True, verbose_name='network service provider')),
                ('tel', models.CharField(blank=True, max_length=13, verbose_name='phone number')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_sender', to=settings.AUTH_USER_MODEL, verbose_name='fund sender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
