# Generated by Django 2.0 on 2018-02-08 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(blank=True, max_length=20, verbose_name='request status')),
                ('response_status', models.CharField(blank=True, max_length=20, verbose_name='response status')),
                ('response_code', models.CharField(blank=True, max_length=15, verbose_name='response code')),
                ('request_type', models.CharField(max_length=20, verbose_name='request type')),
                ('nsp', models.CharField(max_length=15, verbose_name='NSP')),
                ('tel', models.CharField(max_length=20, verbose_name='tel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('transaction_id', models.CharField(blank=True, max_length=30, verbose_name='transaction id')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='request date')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='response date')),
                ('response_transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='response tranx date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
