# Generated by Django 2.0 on 2017-12-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='amount'),
        ),
    ]
