# Generated by Django 2.0 on 2018-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0002_mobilemoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoney',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
    ]
