# Generated by Django 2.0 on 2018-02-22 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purse', '0003_auto_20180209_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='callback_response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='callback response date'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='callback_status_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='callback status code'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='processing_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='processing status'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service Provider'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momo_recipient', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='server_response',
            field=models.CharField(blank=True, max_length=255, verbose_name='server response'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='user_auth',
            field=models.CharField(blank=True, max_length=255, verbose_name='user authentication'),
        ),
        migrations.AddField(
            model_name='mobilemoney',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique verification UUID'),
        ),
        migrations.AlterField(
            model_name='mobilemoney',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momo_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
