# Generated by Django 2.0 on 2017-12-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0004_auto_20171218_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='information',
            field=models.CharField(blank=True, max_length=100, verbose_name='transaction information'),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='transaction status'),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='trans_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='transaction code'),
        ),
    ]
