# Generated by Django 2.0 on 2018-02-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0004_auto_20180222_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='tracker id'),
        ),
    ]
