# Generated by Django 2.0 on 2017-12-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0005_auto_20171218_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='reference',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True, verbose_name='reference'),
        ),
    ]
