# Generated by Django 2.0 on 2018-02-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0005_mobilemoney_tracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
