# Generated by Django 2.0 on 2018-02-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0006_mobilemoney_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='level'),
        ),
    ]
