# Generated by Django 2.0 on 2017-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0007_auto_20171218_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='fees'),
        ),
    ]
