# Generated by Django 2.0 on 2018-01-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0008_auto_20171223_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='tel',
            field=models.CharField(blank=True, max_length=13, verbose_name='phone number'),
        ),
    ]
