# Generated by Django 2.0 on 2018-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0008_mobilemoney_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoney',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='charge'),
        ),
    ]
