# Generated by Django 2.0 on 2018-03-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0009_auto_20180225_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='api unique id'),
        ),
    ]
