# Generated by Django 2.0 on 2018-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0010_mobilemoney_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='tracker id'),
        ),
    ]
