# Generated by Django 2.0 on 2018-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0011_walletmodel_tracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='callback_server_response',
            field=models.CharField(blank=True, max_length=255, verbose_name='callback server response'),
        ),
    ]
