# Generated by Django 2.0 on 2018-09-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0013_mobilemoney_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoney',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='invoice number'),
        ),
    ]
