# Generated by Django 2.0 on 2019-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0015_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoney',
            name='callback_response_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
