# Generated by Django 2.0 on 2017-12-14 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0002_auto_20171212_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='njangitree',
            name='lvel',
        ),
        migrations.AlterField(
            model_name='njangitree',
            name='side',
            field=models.CharField(max_length=1, verbose_name='position side'),
        ),
        migrations.AlterField(
            model_name='njangitree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='child user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient_status',
            field=models.CharField(choices=[('provide_contact', 'provide contact'), ('completed', 'completed'), ('processing', 'processing'), ('cancelled', 'cancelled'), ('suspended', 'suspended')], max_length=20, verbose_name='recipient status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_status',
            field=models.CharField(choices=[('pending_confirmation', 'pending confirmation'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('failed', 'failed')], max_length=20, verbose_name='sender status'),
        ),
    ]
