# Generated by Django 2.0 on 2018-03-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0002_failedoperations_tracker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='package name')),
                ('limit', models.IntegerField(verbose_name='account limits')),
                ('monthly_subscription', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly subscription')),
                ('annual_subscription', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='annual subscription')),
                ('photo', models.FileField(upload_to='account_package/')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=2, verbose_name='account limits')),
                ('related_users', models.CharField(max_length=255, verbose_name='related users')),
                ('last_payment', models.DateTimeField(blank=True, null=True, verbose_name='last payment')),
                ('next_payment', models.DateTimeField(blank=True, null=True, verbose_name='next payment')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='auto renewal')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='njangi.AccountPackage')),
            ],
        ),
    ]
