# Generated by Django 2.0 on 2017-12-16 22:44

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0006_auto_20171216_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njangitree',
            name='user',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='child user'),
        ),
    ]
