# Generated by Django 2.0 on 2018-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0006_auto_20180318_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpackage',
            name='annual_subscription_duration',
            field=models.IntegerField(default=0, verbose_name='annual subscription duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountpackage',
            name='monthly_subscription_duration',
            field=models.IntegerField(default=0, verbose_name='monthly subscription duration'),
            preserve_default=False,
        ),
    ]
