# Generated by Django 2.0 on 2018-03-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0007_auto_20180318_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='package_id',
            new_name='package',
        ),
        migrations.AlterField(
            model_name='accountpackage',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='account_package/'),
        ),
    ]
