# Generated by Django 2.0 on 2017-12-16 22:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0007_auto_20171216_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njangitree',
            name='user',
            field=mptt.fields.TreeOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='child user'),
        ),
    ]
