# Generated by Django 2.0 on 2017-12-16 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0008_auto_20171216_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njangitree',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL, verbose_name='parent user'),
        ),
        migrations.AlterField(
            model_name='njangitree',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='child user'),
        ),
    ]
