# Generated by Django 2.0 on 2018-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0008_auto_20180318_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpackage',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='account limits'),
        ),
    ]
