# Generated by Django 2.0 on 2017-12-17 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0009_auto_20171216_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njangitree',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL, verbose_name='parent user'),
        ),
        migrations.AlterField(
            model_name='njangitree',
            name='side',
            field=models.CharField(blank=True, max_length=1, verbose_name='position side'),
        ),
    ]
