# Generated by Django 2.0 on 2017-12-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0010_auto_20171217_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='payment',
            name='information',
            field=models.CharField(blank=True, max_length=100, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient_status',
            field=models.CharField(choices=[('provide_contact', 'provide contact'), ('complete', 'complete'), ('processing', 'processing'), ('cancelled', 'cancelled'), ('suspended', 'suspended')], max_length=20, verbose_name='recipient status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_status',
            field=models.CharField(choices=[('pending_confirmation', 'pending confirmation'), ('complete', 'complete'), ('cancelled', 'cancelled'), ('failed', 'failed')], max_length=20, verbose_name='sender status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('cancelled', 'cancelled'), ('complete', 'complete')], max_length=20, verbose_name='status'),
        ),
    ]
