# Generated by Django 2.0 on 2018-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0010_useraccount_account_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpackage',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
    ]
