# Generated by Django 2.0 on 2017-12-19 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0011_auto_20171218_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltree',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='leveltree',
            name='last_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last payment date'),
        ),
        migrations.AlterField(
            model_name='leveltree',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_recipient', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='leveltree',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='leveltree',
            name='total_sent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
