# Generated by Django 2.0 on 2017-12-19 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('njangi', '0012_auto_20171219_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='njangi level')),
                ('is_active', models.BooleanField(default=True)),
                ('last_payment', models.DateTimeField(blank=True, null=True, verbose_name='last payment date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_sent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_recipient', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leveltree',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leveltree',
            name='level',
        ),
        migrations.RemoveField(
            model_name='leveltree',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='leveltree',
            name='user',
        ),
        migrations.DeleteModel(
            name='LevelTree',
        ),
        migrations.DeleteModel(
            name='NjangiLevel',
        ),
        migrations.AlterUniqueTogether(
            name='levelmodel',
            unique_together={('user', 'level')},
        ),
    ]
