# Generated by Django 2.0 on 2018-05-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0012_auto_20180326_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemunerationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='level')),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='contribution amount')),
                ('downlines', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='downlines')),
                ('recipient_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='recipient amount')),
                ('company_commission', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='company commission')),
                ('direct_commission', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='direct commission')),
                ('velocity_reserve', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='velocity reserve')),
                ('network_commission', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='network commission')),
            ],
        ),
    ]
