# Generated by Django 2.0 on 2017-12-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('njangi', '0013_auto_20171219_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(blank=True, max_length=100, verbose_name='information')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='level')),
                ('sender_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='sent')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='fees')),
                ('recipient_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='received')),
                ('sender_status', models.CharField(choices=[('pending_confirmation', 'pending confirmation'), ('complete', 'complete'), ('cancelled', 'cancelled'), ('failed', 'failed')], max_length=20, verbose_name='sender status')),
                ('sender_tel', models.CharField(blank=True, max_length=15, verbose_name='sender mobile')),
                ('sender_nsp', models.CharField(choices=[('mtn', 'MTN'), ('orange', 'Orange')], max_length=10)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sent on')),
                ('recipient_status', models.CharField(choices=[('provide_contact', 'provide contact'), ('complete', 'complete'), ('processing', 'processing'), ('cancelled', 'cancelled'), ('suspended', 'suspended')], max_length=20, verbose_name='recipient status')),
                ('recipient_tel', models.CharField(blank=True, max_length=15, verbose_name='sender mobile')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('cancelled', 'cancelled'), ('complete', 'complete')], max_length=20, verbose_name='status')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='completed_on')),
                ('attempts', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='attempts')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
