# Generated by Django 2.0 on 2019-11-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0013_remunerationplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='limit',
            field=models.IntegerField(default=200, verbose_name='account limits'),
        ),
    ]
