# Generated by Django 2.0 on 2017-12-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('njangi', '0014_auto_20171220_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nsp', models.CharField(max_length=20)),
                ('sender_tel', models.CharField(blank=True, max_length=9)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('operation_type', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=150)),
                ('response_status', models.CharField(blank=True, max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='sender',
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
