# Generated by Django 2.0 on 2017-12-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0015_auto_20171223_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmodel',
            name='next_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next payment date'),
        ),
    ]
