# Generated by Django 2.0 on 2017-12-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0016_levelmodel_next_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedoperations',
            name='sender_tel',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
