# Generated by Django 2.0 on 2020-01-24 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Question')),
                ('order', models.IntegerField(verbose_name='order')),
                ('data_type', models.IntegerField(choices=[(1, 'OPTION'), (2, 'TEXT'), (3, 'TEXTAREA')])),
                ('multiple', models.BooleanField(default=False)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback', verbose_name='Feedback ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=300, verbose_name='Response')),
                ('response_date', models.DateTimeField(verbose_name='Response Date')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Question', verbose_name='Question ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='option_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.QuestionOptionTable'),
        ),
    ]
