# Generated by Django 2.0 on 2020-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_list',
        ),
        migrations.AddField(
            model_name='question',
            name='option_list',
            field=models.ManyToManyField(blank=True, null=True, to='feedback.QuestionOptionTable'),
        ),
    ]
