# Generated by Django 2.0 on 2019-12-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.IntegerField(choices=[(1, 'Yes or No'), (2, 'Textfield'), (3, 'Single Checkbox Select'), (4, 'Multiple Checkbox Select')]),
        ),
    ]
