# Generated by Django 2.0 on 2020-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200124_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_type',
            field=models.CharField(choices=[('OPTION', 'OPTION'), ('TEXT', 'TEXT'), ('TEXTAREA', 'TEXTAREA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_list',
            field=models.ManyToManyField(blank=True, to='feedback.QuestionOptionTable'),
        ),
    ]
