# Generated by Django 2.0 on 2019-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20191209_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
    ]
