# Generated by Django 2.0 on 2019-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20191209_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
            preserve_default=False,
        ),
    ]
