# Generated by Django 2.0 on 2018-09-03 22:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
