# Generated by Django 2.0 on 2018-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_commission_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='net_payable',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='net payable'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_discount',
            field=models.BooleanField(default=False, verbose_name='allow discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3, verbose_name='discount rate'),
        ),
    ]
