# Generated by Django 2.0 on 2019-08-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20180929_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
