# Generated by Django 2.0 on 2018-04-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('image', models.FileField(blank=True, upload_to='blog/category/sub/', verbose_name='image')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('image', models.FileField(blank=True, upload_to='blog/category/main/', verbose_name='image')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', tinymce.models.HTMLField(verbose_name='news content')),
                ('image', models.FileField(blank=True, upload_to='blog/category/sub/', verbose_name='image')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.MainCategory', verbose_name='main category'),
        ),
    ]
