# Generated by Django 2.0 on 2018-02-14 17:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='*', max_length=30, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='*', max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='last name'),
        ),
    ]
