# Generated by Django 2.0 on 2017-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171207_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upline',
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.PositiveIntegerField(default=1, verbose_name='sponsor'),
            preserve_default=False,
        ),
    ]
