# Generated by Django 2.0 on 2018-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180318_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_account_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='user account id'),
        ),
    ]
