# Generated by Django 2.0 on 2017-12-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171210_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsor',
            field=models.PositiveIntegerField(db_index=True, verbose_name='sponsor'),
        ),
    ]
