# Generated by Django 2.0 on 2017-12-17 22:58

import django.contrib.auth.models
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171214_0814'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', main.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsor',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='sponsor'),
        ),
    ]
