# Generated by Django 2.0 on 2017-12-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='level'),
        ),
    ]
