# Generated by Django 2.0 on 2019-09-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190817_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='network_parent',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='network parent'),
        ),
    ]
