# Generated by Django 2.0 on 2019-11-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_network_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_phone_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
