# Generated by Django 2.0 on 2017-12-29 08:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171226_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='*', max_length=128, null=True, verbose_name='Orange number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='*', max_length=128, null=True, verbose_name='Nexttel number'),
        ),
    ]
