# Generated by Django 2.0 on 2017-12-30 22:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171229_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='optional', max_length=128, null=True, verbose_name='Nexttel number'),
        ),
    ]
