# Generated by Django 2.0 on 2017-12-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171230_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_automatic_contribution',
            field=models.BooleanField(default=False, verbose_name='allow automatic contributions'),
        ),
    ]
