# Generated by Django 2.0 on 2018-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_allow_automatic_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='level')),
                ('downlines', models.PositiveIntegerField(verbose_name='downlines')),
                ('cumm_downlines', models.PositiveIntegerField(verbose_name='cumm. downlines')),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='contribution')),
                ('receipts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='receipts')),
                ('cumm_receipts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cumm. receipts')),
                ('cumm_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cumm. contribution')),
                ('monthly_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly profit')),
                ('upgrade_after', models.CharField(blank=True, max_length=30, verbose_name='upgrade after')),
            ],
        ),
    ]
