# Generated by Django 2.0 on 2018-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180109_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='upgrade_after',
            field=models.PositiveIntegerField(default=0, verbose_name='upgrade after'),
        ),
    ]
