# Generated by Django 2.0 on 2018-01-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180109_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_automatic_contribution',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False, verbose_name='allow automatic contributions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exist.'}, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
