# Generated by Django 2.0 on 2018-01-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180111_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_automatic_contribution',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=False, verbose_name='allow automatic contributions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@gmail.com', error_messages={'unique': 'email already exist.'}, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
