# Generated by Django 2.0 on 2018-01-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180113_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'email already exist.'}, help_text='*', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
