# Generated by Django 2.0 on 2018-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180113_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'email already exist.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
