

# Monetbil Authentication info

MONETBIL_NJANGI_NETWORK_SERVICE_KEY = 'IUQTPgsgejfni20P6NntjVfHkMTe4iuY'
MONETBIL_NJANGI_NETWORK_SERVICE_SECRET = 'IA7CBtfvsrOXU95jZXsrYybeA1QUzkUALco7xnBdcFzYnb7xicnehZJVkqBUTBdl'

PROTOCOL = 'https://'
